name: Build and Publish storybook to GitHub Pages

on:
  pull_request:
    branches: [dev]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Packages
        run: npm install

      - name: Build Storybook
        run: npm run build-storybook-docs

      - name: Print Contents of storybook-static
        run: ls -R storybook-static

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: dev
          folder: storybook-static
